# Generated by Django 5.0.12 on 2025-03-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reply_to',
        ),
    ]
